2021-03-24 02:43:03,133 ERROR    Processes plugin raised an exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/landscape/sysinfo/sysinfo.py", line 99, in run
    result = plugin.run()
  File "/usr/lib/python3/dist-packages/landscape/sysinfo/processes.py", line 17, in run
    info = ProcessInformation(proc_dir=self._proc_dir)
  File "/usr/lib/python3/dist-packages/landscape/lib/process.py", line 29, in __init__
    self._jiffies_per_sec = jiffies or detect_jiffies()
  File "/usr/lib/python3/dist-packages/landscape/lib/jiffies.py", line 42, in detect_jiffies
    jiffies1 = int(jiffie_uptime/seconds_uptime1+0.5)
ZeroDivisionError: float division by zero
2021-04-03 03:33:10,401 ERROR    Processes plugin raised an exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/landscape/sysinfo/sysinfo.py", line 99, in run
    result = plugin.run()
  File "/usr/lib/python3/dist-packages/landscape/sysinfo/processes.py", line 17, in run
    info = ProcessInformation(proc_dir=self._proc_dir)
  File "/usr/lib/python3/dist-packages/landscape/lib/process.py", line 29, in __init__
    self._jiffies_per_sec = jiffies or detect_jiffies()
  File "/usr/lib/python3/dist-packages/landscape/lib/jiffies.py", line 42, in detect_jiffies
    jiffies1 = int(jiffie_uptime/seconds_uptime1+0.5)
ZeroDivisionError: float division by zero
